# Generated by Django 3.2 on 2021-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_supplier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
